version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile.github_action
    ports:
      - "8080:80"
    environment:
      # ... other environment variables
      - GITHUB_EVENT_PATH=/app/event.json  # Correct path in the container
      - GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME}
      - OPENAI_KEY=${OPENAI_KEY}
      - OPENAI_ORG=${OPENAI_ORG}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./github/workflow:/app  # Mount the event payload as a volume

